In [1]:
from engine.data import get_commands_loader, get_main_classes_loader

import torch

In [2]:
loader = get_commands_loader('train')

ys = []

for X, y in loader:
    ys.append(y)
    
ys = torch.concat(ys)

ys.unique(return_counts=True)

(tensor([ 0,  1,  2,  3,  4,  5,  6,  8, 10, 11], device='cuda:0'),
 tensor([1842, 1861, 1839, 1853, 1839, 1864, 1852, 1885, 1843, 1860],
        device='cuda:0'))

In [3]:
loader = get_main_classes_loader('train')

ys = []

for X, y in loader:
    ys.append(y)
    
ys = torch.concat(ys)

ys.unique(return_counts=True)

(tensor([0, 1, 2], device='cuda:0'),
 tensor([18538, 32550,  2430], device='cuda:0'))